### ISSUE TITLE
Add support for command line validation of ODF documents using ODF Toolkit

### ISSUE THREAD

**Issue by kjambunathan** [kjambunathan/org-mode-ox-odt#125]
Add support for command line validation of ODF documents using ODF Toolkit.  Also explore other possible integrations.

See https://odftoolkit.org/conformance/ODFValidator.html

**Comment by kjambunathan** [comment]
## Grab a corrupt file 

Copy `test.odt` from https://github.com/kjambunathan/org-mode-ox-odt/issues/62#issuecomment-559340682 and rename it as `corrupt.odt`

## Download `odfvaidator`

There are atleast three sources for `odfvaidator`

###  Variant 1 of `odfvaidator`

Download Page: [Central Repository: org/odftoolkit/odfvalidator/1.0.0-BETA1](https://repo.maven.apache.org/maven2/org/odftoolkit/odfvalidator/1.0.0-BETA1/)

JAR file:  [odfvalidator-1.0.0-BETA1-jar-with-dependencies.jar](https://repo.maven.apache.org/maven2/org/odftoolkit/odfvalidator/1.0.0-BETA1/odfvalidator-1.0.0-BETA1-jar-with-dependencies.jar)


$ java -jar odfvalidator-1.0.0-BETA1-jar-with-dependencies.jar -h
    usage: odfvalidator -g <odffiles>
	   odfvalidator [-r] [-c|-e|-s] [-d] [-v|-w] [-f <filterfile>] [-x <regexp>] [-o outputfile] [-1.0|-1.1|-1.2] <odffiles>
	   odfvalidator [-r] [-c|-e|-s] [-d] [-v|-w] [-f <filterfile>] [-x <regexp>] [-o outputfile] -S <schemafile> <odffiles>
	   odfvalidator [-r] [-c|-e|-s] [-v|-w] -O <rngfile> -M <rngfile> -D <rngfile> -m <xsdfile> [-f <filterfile>] [-x <regexp>] [-o outputfile] <odffiles>
	   odfvalidator [-c|-s] [-v|-w] [-d] [-o outputfile] -C <configfile>
	   odfvalidator -h
	   odfvalidator -V

    -C: Validate using configuration file <configfile>
    -S: Use strict ODF schema <schemafile> for validation
    -O: Use ODF schema <schemafile> for validation
    -M: Use ODF manifest schema <schemafile> for validation
    -D: Use ODF dsig schema <schemafile> for validation
    -m: Use MathML2 schema <schemafile> for validation
    -V: Print version
    -c: Check conformance (default for ODF 1.2 documents)
    -e: Check extended conformance (ODF 1.2 documents only)
    -d: Use MathML DTD rather than MathML2 schema for validation
    -f: Use filterfile <filterfile>
    -g: Show <odffiles> generators and exit
    -h: Print this help and exit
    -o: Store validation errors in <outputfile>
    -r: Process directory recursively
    -s: Validate against strict schema (ODF 1.0/1.1 documents only)
    -v: Verbose output, including generator and warnings
    -w: Print warnings
    -x: Exclude paths that match <regexp>

    If no option is provided, <odffiles> are validated using the schemas matching the detected ODF version of the files


$ java -jar odfvalidator-1.0.0-BETA1-jar-with-dependencies.jar -v  corrupt.odt

    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt:  Info: ODF version of root document: 1.2
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/mimetype:  Error: The ODF package 'file:///home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt' contains a 'mimetype' file containing 'application/vnd.oasis.opendocument.text', which differs from the mediatype of the root document 'application/vnd.oasis.opendocument.text'!
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt:  Error: The ODF mimetype 'application/vnd.oasis.opendocument.text' is invalid for the ODF XML Schema document!
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/mimetype:  Info: mimetype is not an ODFMediaTypes mimetype.
    internal:/schema/odf1.2/OpenDocument-v1.2-os-manifest-schema.rng:  Info: parsed.
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/META-INF/manifest.xml:  Info: no errors, no warnings
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/mimetype:  Info: 1 errors, no warnings
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt:  Info: Media Type: application/vnd.oasis.opendocument.text
    internal:/schema/odf1.2/OpenDocument-v1.2-os-schema.rng:  Info: parsed.
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/meta.xml:  Info: no errors, no warnings
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/styles.xml:  Info: no errors, no warnings
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/content.xml:  Info: no errors, no warnings
    internal:/schema/odf1.2/OpenDocument-v1.2-os-dsig-schema.rng:  Info: parsed.
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt:  Info: 2 errors, no warnings


## Variant 2 of `odfvalidator`

Download Page: [Maven Central Repository Search](https://search.maven.org/search?q=g:org.apache.odftoolkit%20AND%20a:odfvalidator)

JAR file :  [odfvalidator-1.1.8-incubating-jar-with-dependencies.jar](https://repo1.maven.org/maven2/org/apache/odftoolkit/odfvalidator/1.1.8-incubating/odfvalidator-1.1.8-incubating-jar-with-dependencies.jar)

$ java -jar odfvalidator-1.1.8-incubating-jar-with-dependencies.jar -v
    usage: odfvalidator -g <odffiles>
	   odfvalidator [-r] [-c|-e|-s] [-d] [-v|-w] [-f <filterfile>] [-x <regexp>] [-o outputfile] [-1.0|-1.1|-1.2] <odffiles>
	   odfvalidator [-r] [-c|-e|-s] [-d] [-v|-w] [-f <filterfile>] [-x <regexp>] [-o outputfile] -S <schemafile> <odffiles>
	   odfvalidator [-c|-s] [-v|-w] [-d] [-o outputfile] -C <configfile>
	   odfvalidator -h
	   odfvalidator -V

    -C: Validate using configuration file <configfile>
    -S: Use strict ODF schema <schemafile> for validation
    -O: Use ODF schema <schemafile> for validation
    -M: Use ODF manifest schema <schemafile> for validation
    -D: Use ODF dsig schema <schemafile> for validation
    -V: Print version
    -c: Check conformance (default for ODF 1.2 documents)
    -e: Check extended conformance (ODF 1.2 documents only)
    -d: Use MathML DTD rather than MathML2 schema for validation
    -f: Use filterfile <filterfile>
    -g: Show <odffiles> generators and exit
    -h: Print this help and exit
    -o: Store validation errors in <outputfile>
    -r: Process directory recursively
    -s: Validate against strict schema (ODF 1.0/1.1 documents only)
    -v: Verbose output, including generator and warnings
    -w: Print warnings
    -x: Exclude paths that match <regexp>

    If no option is provided, <odffiles> are validated using the schemas matching the detected ODF version of the files


$ java -jar odfvalidator-1.1.8-incubating-jar-with-dependencies.jar -v -w corrupt.odt
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt/mimetype:  Error: The ODF package 'file:///home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt' contains a 'mimetype' file containing 'application/vnd.oasis.opendocument.text', which differs from the mediatype of the root document 'application/vnd.oasis.opendocument.text'!
    /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/corrupt.odt:  Error: The ODF mimetype 'application/vnd.oasis.opendocument.text' is invalid for the ODF XML Schema document!
    Exception in thread "main" java.lang.NullPointerException
	    at org.odftoolkit.odfvalidator.ODFValidator.getValidatorForSchema(ODFValidator.java:286)
	    at org.odftoolkit.odfvalidator.ODFValidator.getManifestValidator(ODFValidator.java:186)
	    at org.odftoolkit.odfvalidator.ODFRootPackageValidator.validateManifest(ODFRootPackageValidator.java:170)
	    at org.odftoolkit.odfvalidator.ODFRootPackageValidator.validatePre(ODFRootPackageValidator.java:93)
	    at org.odftoolkit.odfvalidator.ODFPackageValidator._validate(ODFPackageValidator.java:111)
	    at org.odftoolkit.odfvalidator.ODFPackageValidator.validate(ODFPackageValidator.java:81)
	    at org.odftoolkit.odfvalidator.ODFValidator.validateFile(ODFValidator.java:163)
	    at org.odftoolkit.odfvalidator.ODFValidator.validate(ODFValidator.java:124)
	    at org.odftoolkit.odfvalidator.Main.main(Main.java:294)




## Variant 3 of `odfvaidator`

ODF Validator hosted by LibreOffice / DocumentFoundation [ODF Validator 1.3](https://odfvalidator.org/)

I am not sure if the number `1.3` above is the version of binary jar file, or the version of OpenDocumentSchema

Running the above validator on `corrupt.odt` reports

    The document is NOT conformant ODF1.2!
    Details:
    corrupt.odt: Info: ODF version of root document: 1.2
    corrupt.odt/mimetype: Error: The ODF package 'corrupt.odt' contains a 'mimetype' file containing 'application/vnd.oasis.opendocument.text', which differs from the mediatype of the root document 'application/vnd.oasis.opendocument.text'!
    corrupt.odt: Error: The ODF mimetype 'application/vnd.oasis.opendocument.text' is invalid for the ODF XML Schema document!
    corrupt.odt/mimetype: Error: mimetype is not an ODFMediaTypes mimetype.
    internal:/schema/odf1.2/OpenDocument-v1.2-os-manifest-schema.rng: Info: parsed.
    corrupt.odt/META-INF/manifest.xml: Info: no errors, no warnings
    corrupt.odt/mimetype: Info: 2 errors, no warnings
    corrupt.odt: Info: Media Type: application/vnd.oasis.opendocument.text
    internal:/schema/odf1.2/OpenDocument-v1.2-os-schema.rng: Info: parsed.
    corrupt.odt/meta.xml: Info: no errors, no warnings
    corrupt.odt/styles.xml: Info: no errors, no warnings
    corrupt.odt/content.xml: Info: no errors, no warnings
    internal:/schema/odf1.2/OpenDocument-v1.2-os-dsig-schema.rng: Info: parsed.
    corrupt.odt: Info: 3 errors, no warnings

## Additional Notes

- Note that the  variant 2 throws a stacktrace.  But going by the version number alone  it seems to be an advanced, but an unstable one.  
- Note that  variant 3 reports 3 errors but variant 1 reports 2 errors.

Since we want a command-line validator, as opposed to web-hosted one validator 1 is the only option out at the time of writing
So, go with Variant 1 above.

**Comment by kjambunathan** [comment]
> Since we want a command-line validator, as opposed to web-hosted one validator 1 is the only option out at the time of writing
> So, go with Variant 1 above.

Scratch that.

There exists another variant of `odfvalidator` which is right there in
https://odftoolkit.org/ page which I have missed.  There are two
binaries one targetting `JDK 8` and other targetting `JDK 11`.  

This release doesn't suffer from NullPointer exception reported in
some variants above.  So, this binary is the one that needs to be
used.

###  Variant 4 of `odfvaidator`

**Download Page**: [ODF Toolkit](https://odftoolkit.org/downloads.html)

**JAR file**:  

- [ODF Validator 0.10.0 (ODF 1.2 using JDK 11)](https://repo1.maven.org/maven2/org/odftoolkit/odfvalidator/0.10.0/)
- [ODF Validator 0.9.0 (ODF 1.2 using JDK 8)](https://repo1.maven.org/maven2/org/odftoolkit/odfvalidator/0.9.0/)


	~$ java -jar ./odfvalidator-0.10.0-jar-with-dependencies.jar -v
	usage: odfvalidator -g <odffiles>
		   odfvalidator [-r] [-c|-e|-s] [-d] [-v|-w] [-f <filterfile>] [-x <regexp>] [-o outputfile] [-1.0|-1.1|-1.2|1.3] <odffiles>
		   odfvalidator [-r] [-c|-e|-s] [-d] [-v|-w] [-f <filterfile>] [-x <regexp>] [-o outputfile] -S <schemafile> <odffiles>
		   odfvalidator [-r] [-c|-e|-s] [-v|-w] -O <rngfile> -M <rngfile> -D <rngfile> -m <xsdfile> [-f <filterfile>] [-x <regexp>] [-o outputfile] <odffiles>
		   odfvalidator [-c|-s] [-v|-w] [-d] [-o outputfile] -C <configfile>
		   odfvalidator -h
		   odfvalidator -V

	-C: Validate using configuration file <configfile>
	-S: Use strict ODF schema <schemafile> for validation
	-O: Use ODF schema <schemafile> for validation
	-M: Use ODF manifest schema <schemafile> for validation
	-D: Use ODF dsig schema <schemafile> for validation
	-m: Use specific MathML schema <schemafile> for validation
	-V: Print version
	-c: Check conformance (default for ODF 1.2 and 1.3 documents)
	-e: Check extended conformance (ODF 1.2 and 1.3 documents only)
	-d: deprecated and ignored; Whether to use MathML DTD or MathML2 schema for validation is auto-detected
	-f: Use filterfile <filterfile>
	-g: Show <odffiles> generators and exit
	-h: Print this help and exit
	-o: Store validation errors in <outputfile>
	-r: Process directory recursively
	-s: Validate against strict schema (ODF 1.0/1.1 documents only)
	-v: Verbose output, including generator and warnings
	-w: Print warnings
	-x: Exclude paths that match <regexp>

	If no option is provided, <odffiles> are validated using the schemas matching the detected ODF version of the files

	~$ java -jar ./odfvalidator-0.10.0-jar-with-dependencies.jar -v ./corrupt.odt 

	./corrupt.odt:  Info: ODF version of root document: 1.2
	./corrupt.odt/mimetype:  Error: The ODF package 'file://./corrupt.odt' contains a 'mimetype' file containing 'application/vnd.oasis.opendocument.text', which differs from the mediatype of the root document 'application/vnd.oasis.opendocument.text'!
	./corrupt.odt:  Error: The ODF mimetype 'application/vnd.oasis.opendocument.text' is invalid for the ODF XML Schema document!
	./corrupt.odt/mimetype:  Error: mimetype is not an ODFMediaTypes mimetype.
	internal:/schema/odf1.2/OpenDocument-v1.2-os-manifest-schema.rng:  Info: parsed.
	./corrupt.odt/META-INF/manifest.xml:  Info: no errors, no warnings
	./corrupt.odt/mimetype:  Info: 2 errors, no warnings
	./corrupt.odt:  Info: Media Type: application/vnd.oasis.opendocument.text
	internal:/schema/odf1.2/OpenDocument-v1.2-os-schema.rng:  Info: parsed.
	./corrupt.odt/meta.xml:  Info: no errors, no warnings
	./corrupt.odt/styles.xml:  Info: no errors, no warnings
	./corrupt.odt/content.xml:  Info: no errors, no warnings
	internal:/schema/odf1.2/OpenDocument-v1.2-os-dsig-schema.rng:  Info: parsed.
	./corrupt.odt:  Info: 3 errors, no warnings

**Comment by kjambunathan** [comment]
### Test snippet

```
#+odt_preferred_output_format: pdf

#+odt_validate: abort
# #+odt_validate: noabort

#+begin_src emacs-lisp :exports results :results silent
(custom-set-variables
 '(org-odt-validate-process
   '("java" "-jar" "/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/odfvalidator-0.10.0-jar-with-dependencies.jar" "-v" "%i"))
 )
org-odt-vaidate-process
#+end_src

A very simple document.

# Local Variables:
# org-export-use-babel: t
# End:
```

### Results

Note the last few lines ...

```
org-babel-exp process emacs-lisp at position 86...
executing Emacs-Lisp code block...
("java" "-jar" "/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/odfvalidator-0.10.0-jar-with-dependencies.jar" "-v" "%i")
ODT Zip Dir is /tmp/odt-F3J97U/
Formatting LaTeX using mathml
ox-odt: Content template file is /home/kjambunathan/src/org-mode-ox-odt-master/etc/styles/OrgOdtContentTemplate.xml
Using schema ~/src/org-mode-ox-odt-master/etc/schema/od-schema.rnc
Saving file /tmp/odt-F3J97U/content.xml...
Wrote /tmp/odt-F3J97U/content.xml
ox-odt: Styles file is /home/kjambunathan/src/org-mode-ox-odt-master/etc/styles/OrgOdtStyles.xml
Using schema ~/src/org-mode-ox-odt-master/etc/schema/od-schema.rnc
Saving file /tmp/odt-F3J97U/styles.xml...
Wrote /tmp/odt-F3J97U/styles.xml
Using schema ~/src/org-mode-ox-odt-master/etc/schema/od-schema.rnc
Saving file /tmp/odt-F3J97U/meta.xml...
Wrote /tmp/odt-F3J97U/meta.xml
Wrote /tmp/odt-F3J97U/mimetype
Using schema ~/src/org-mode-ox-odt-master/etc/schema/od-manifest-schema.rnc
Saving file /tmp/odt-F3J97U/META-INF/manifest.xml...
Wrote /tmp/odt-F3J97U/META-INF/manifest.xml
Create OpenDocument file ‘20211210.odt’...
Using schema ~/src/org-mode-ox-odt-master/etc/schema/od-schema.rnc
Running zip -mX0 20211210.odt mimetype
Running zip -rmTq 20211210.odt .
Created /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt
Validating file ‘/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt’ ...
Running java -jar /home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/odfvalidator-0.10.0-jar-with-dependencies.jar -v 20211210.odt
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt:  Info: ODF version of root document: 1.2
	internal:/schema/odf1.2/OpenDocument-v1.2-os-manifest-schema.rng:  Info: parsed.
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/META-INF/manifest.xml:  Info: no errors, no warnings
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/mimetype:  Info: no errors, no warnings
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt:  Info: Media Type: application/vnd.oasis.opendocument.text
	internal:/schema/odf1.2/OpenDocument-v1.2-os-schema.rng:  Info: parsed.
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/meta.xml:  Info: no errors, no warnings
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/styles.xml[316,215]:  Error: unexpected attribute "style:contextual-spacing"
	6pt solid #000000" style:shadow="none"
	                                 ----^
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/styles.xml[324,112]:  Error: unexpected attribute "style:contextual-spacing"
	1cm" style:contextual-spacing="false"/
	                                 ----^
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/styles.xml:  Info: 2 errors, no warnings
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt/content.xml:  Info: no errors, no warnings
	internal:/schema/odf1.2/OpenDocument-v1.2-os-dsig-schema.rng:  Info: parsed.
	/home/kjambunathan/src/org-mode-ox-odt/testing/examples/odt/20211210.odt:  Info: 2 errors, no warnings

condition-case: OpenDocument export failed with error: ‘File ‘20211210.odt’ is malformed’
```
